data_sources:
  - name: dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: analytics_db
    type: postgres
    key: ${ANALYTICS_DB_URL}

jobs:
  - name: d2p-cow_protocol_${BLOCKCHAIN}_vouches
    source:
      ref: dune
      query_id: 4871726
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__cow_protocol_${BLOCKCHAIN}_vouches
      if_exists: upsert
      index_columns:
        - evt_tx_hash
        - evt_index

  - name: d2p-cow_protocol_${BLOCKCHAIN}_invalidated_vouches
    source:
      ref: dune
      query_id: 4871740
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__cow_protocol_${BLOCKCHAIN}_invalidated_vouches 
      if_exists: upsert
      index_columns:
        - evt_tx_hash
        - evt_index

  - name: d2p-cow_protocol_${BLOCKCHAIN}_solvers
    source:
      ref: dune
      query_id: 4345829
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__cow_protocol_${BLOCKCHAIN}_solvers
      if_exists: upsert
      index_columns:
        - active
        - address
        - environment
        - name

#hard coded data, not big
#todo check with felix how to parameterise this query per chain
  - name: d2p-cow_protocol_ethereum_excluded_batches
    source:
      ref: dune
      query_id: 3490353
      query_engine: medium
      poll_frequency: 5
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__cow_protocol_ethereum_excluded_batches
      if_exists: upsert
      index_columns:
        - tx_hash

  - name: d2p-raw_slippage
    source:
      ref: dune
      query_id: 4059683 
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: start_time
          value: ${ACCOUNTING_PERIOD_START_TIME} 
          type: DATE
        - name: end_time
          value: ${ACCOUNTING_PERIOD_END_TIME}
          type: DATE
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
        - name: raw_slippage_table_name #todo: check with felix if this table is called differently for other chains
          value: raw_slippage_breakdown
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__raw_slippage

  - name: d2p-cow_protocol_${BLOCKCHAIN}_batches
    source:
      ref: dune
      query_id: 4468789
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: start_time
          value: ${ACCOUNTING_PERIOD_START_TIME}
          type: DATE
        - name: end_time
          value: ${ACCOUNTING_PERIOD_END_TIME}
          type: DATE
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__cow_protocol_${BLOCKCHAIN}_batches
      if_exists: upsert
      index_columns:
        - tx_hash

  - name: d2p-service_fee_tracker
    source:
      ref: dune
      query_id: 4617513
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: start_time
          value: ${ACCOUNTING_PERIOD_START_TIME}
          type: DATE
        - name: end_time
          value: ${ACCOUNTING_PERIOD_END_TIME}
          type: DATE
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__service_fee_tracker
      if_exists: upsert
      index_columns:
        - solver
        - start_time
        - end_time

  - name: d2p-block-timestamp
    source:
      ref: dune
      query_id: 4599974
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: start_time
          value: ${ACCOUNTING_PERIOD_START_TIME}
          type: DATE
        - name: end_time
          value: ${ACCOUNTING_PERIOD_END_TIME}
          type: DATE
        - name: blockchain
          value: ${BLOCKCHAIN}
          type: ENUM
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__block_timestamp
      if_exists: upsert
      index_columns:
        - block_number

  - name: d2p-conversion-rate-accounting-period
    source:
      ref: dune
      query_id: 4545357
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: start_time
          value: ${ACCOUNTING_PERIOD_START_TIME}
          type: DATE
        - name: end_time
          value: ${ACCOUNTING_PERIOD_END_TIME}
          type: DATE
    destination:
      ref: analytics_db
      table_name: dbt_local_test.dune_data__conversion_rate_per_accounting_period
      if_exists: upsert
      index_columns:
        - conversion_rate_cow_to_native
        - end_time
        - start_time